from world import WorldBuilder

world = (WorldBuilder()
    .add_route("BK", ["Bengaluru", "A", "B", "C", "D", "Kochi"])
    .add_route("KB", ["Kochi", "D", "C", "B", "A", "Bengaluru"])
    .add_connection("Bengaluru", "A", 100)
    .add_connection("A", "B", 120)
    .add_connection("B", "C", 100)
    .add_connection("C", "D", 120)
    .add_connection("D", "Kochi", 100)
    .add_stop("Bengaluru", 0)
    .add_stop("A", 1)
    .add_stop("B", 1)
    .add_stop("C", 1)
    .add_stop("D", 1)
    .add_stop("Kochi", 0)
    .load_csv("Scenarios/1.csv")
    .build()
)

world.show()
